[ALLEEG EEG CURRENTSET ALLCOM] = eeglab;
EEG = pop_loadset('filename','eeglab_data.set','filepath','C:\\Users\\mehme\\AppData\\Roaming\\MathWorks\\MATLAB Add-Ons\\Collections\\EEGLAB\\sample_data\\');
[ALLEEG, EEG, CURRENTSET] = eeg_store( ALLEEG, EEG, 0 );
EEG = pop_eegfiltnew(EEG, 'locutoff',1,'plotfreqz',1);
[ALLEEG EEG CURRENTSET] = pop_newset(ALLEEG, EEG, 1,'setname','EkizZehra_eegdata_highpass_1hz.','savenew','Ekizzehra_eegdata_highpass_1hz.','gui','off'); 
EEG = eeg_checkset( EEG );
figure; pop_spectopo(EEG, 1, [0      238304.6875], 'EEG' , 'freq', [6 10 22], 'freqrange',[0 60],'electrodes','off');
EEG = eeg_checkset( EEG );
pop_prop( EEG, 1, [3   4   5  12  13  14  21  22  23], NaN, {'freqrange',[0 60] });
EEG = pop_eegfiltnew(EEG, 'hicutoff',50,'plotfreqz',1);
[ALLEEG EEG CURRENTSET] = pop_newset(ALLEEG, EEG, 2,'setname','EkizZehra_eegdata_lowpass_50hz.','savenew','EkizZehra_eegdata_lowpass_50hz.','gui','off'); 
EEG = eeg_checkset( EEG );
pop_prop( EEG, 1, [3   4   5  12  13  14  21  22  23], NaN, {'freqrange',[0 60] });
EEG = eeg_checkset( EEG );
figure; pop_spectopo(EEG, 1, [0      238304.6875], 'EEG' , 'freq', [6 10 22], 'freqrange',[0 60],'electrodes','off');
[ALLEEG EEG CURRENTSET ALLCOM] = eeglab;
EEG = pop_loadset('filename','Ekizzehra_eegdata_highpass_1hz.set','filepath','C:\\Users\\mehme\\AppData\\Roaming\\MathWorks\\MATLAB Add-Ons\\Collections\\EEGLAB\\');
[ALLEEG, EEG, CURRENTSET] = eeg_store( ALLEEG, EEG, 0 );
EEG = pop_loadset('filename','EkizZehra_eegdata_lowpass_50hz.set','filepath','C:\\Users\\mehme\\AppData\\Roaming\\MathWorks\\MATLAB Add-Ons\\Collections\\EEGLAB\\');
[ALLEEG, EEG, CURRENTSET] = eeg_store( ALLEEG, EEG, 0 );
EEG = eeg_checkset( EEG );
EEG = pop_reref( EEG, []);
[ALLEEG EEG CURRENTSET] = pop_newset(ALLEEG, EEG, 2,'setname','EkizZehra_eegdata_avgReference','savenew','EkizZehra_eegdata_avgReference','gui','off'); 
EEG = eeg_checkset( EEG );
pop_prop( EEG, 1, [3   4   5  12  13  14  21  22  23], NaN, {'freqrange',[0 60] });
EEG = eeg_checkset( EEG );
figure; pop_spectopo(EEG, 1, [0      238304.6875], 'EEG' , 'freq', [6 10 22], 'freqrange',[0 60],'electrodes','off');
[ALLEEG EEG CURRENTSET ALLCOM] = eeglab;
EEG = pop_loadset('filename','EkizZehra_eegdata_avgReference.set','filepath','C:\\Users\\mehme\\AppData\\Roaming\\MathWorks\\MATLAB Add-Ons\\Collections\\EEGLAB\\');
[ALLEEG, EEG, CURRENTSET] = eeg_store( ALLEEG, EEG, 0 );
EEG = eeg_checkset( EEG );
EEG = pop_epoch( EEG, {  'square'  }, [-1  2], 'newname', 'EkizZehra_eegdata_avgReference epochs', 'epochinfo', 'yes');
[ALLEEG EEG CURRENTSET] = pop_newset(ALLEEG, EEG, 1,'savenew','EkizZehra_eegdata_avgReference epochs','gui','off'); 
EEG = eeg_checkset( EEG );
EEG = pop_rmbase( EEG, [-1000 0] ,[]);
[ALLEEG EEG CURRENTSET] = pop_newset(ALLEEG, EEG, 2,'setname','EkizZehra_eegdata_epoched','savenew','EkizZehra_eegdata_epoched','gui','off'); 
[ALLEEG EEG CURRENTSET ALLCOM] = eeglab;
EEG = pop_loadset('filename','EkizZehra_eegdata_epoched.set','filepath','C:\\Users\\mehme\\AppData\\Roaming\\MathWorks\\MATLAB Add-Ons\\Collections\\EEGLAB\\');
[ALLEEG, EEG, CURRENTSET] = eeg_store( ALLEEG, EEG, 0 );
EEG = eeg_checkset( EEG );
EEG = pop_jointprob(EEG,1,[1:32] ,5,5,0,0,0,[],0);
EEG = pop_rejkurt(EEG,1,[1:32] ,5,5,0,0,0,[],0);
EEG = eeg_rejsuperpose( EEG, 1, 1, 1, 1, 1, 1, 1, 1);
EEG = pop_rejepoch( EEG, [11 12 16 57 69] ,0);
[ALLEEG EEG CURRENTSET] = pop_newset(ALLEEG, EEG, 1,'setname','EkizZehra_eegdata_artifactRejected','savenew','EkizZehra_eegdata_artifactRejected','gui','off'); 